[package]
name = "yane2"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bitflags = "2.5.0"
clap = { version = "4.5.7", features = ["derive"] }
eyre = "0.6.12"
macroquad = { version = "0.4.2", features = ["audio", "log"] }
